name: Docker build & push to Kyndryl MCMP Artifactory
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["MMM App Manager build"]
    types: 
      - completed
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Kyndryl Jfrog Artifactory
        uses: docker/login-action@v1
        with:
          registry: na.artifactory.taas.kyndryl.net
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
#$$$
